import java.awt.*;
import java.io.*;

/**
 *
 * @author  Administrator
 */
public class HideFile extends javax.swing.JFrame {
    
    /** Creates new form HideFile */
    public HideFile() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filebrowsebtn2 = new javax.swing.JButton();
        bmpfilepath = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        hidebtn = new javax.swing.JButton();
        filesize = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bmpsize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        filecapacity = new javax.swing.JTextField();
        closebtn = new javax.swing.JButton();
        sourcepath = new javax.swing.JTextField();
        filebrowsebtn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        targetfilepath = new javax.swing.JTextField();
        filebrowsebtn3 = new javax.swing.JButton();
        showmsg = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hide File");
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel1.setText("Source File :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(7, 20, 67, 15);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel2.setText("Bitmap File :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 70, 15);

        filebrowsebtn2.setText("...");
        filebrowsebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebrowsebtn2ActionPerformed(evt);
            }
        });

        getContentPane().add(filebrowsebtn2);
        filebrowsebtn2.setBounds(500, 50, 30, 23);

        getContentPane().add(bmpfilepath);
        bmpfilepath.setBounds(80, 50, 420, 20);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 70, 15);

        getContentPane().add(password);
        password.setBounds(80, 80, 360, 22);

        hidebtn.setText("Hide");
        hidebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidebtnActionPerformed(evt);
            }
        });

        getContentPane().add(hidebtn);
        hidebtn.setBounds(440, 80, 90, 23);

        filesize.setEditable(false);
        getContentPane().add(filesize);
        filesize.setBounds(170, 170, 100, 20);

        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 530, 10);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel4.setText("File Size :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 170, 90, 15);

        jLabel5.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel5.setText("Bitmap Size :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 200, 90, 15);

        bmpsize.setEditable(false);
        getContentPane().add(bmpsize);
        bmpsize.setBounds(170, 200, 100, 20);

        jLabel6.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel6.setText("File Capacity :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 170, 74, 15);

        filecapacity.setEditable(false);
        getContentPane().add(filecapacity);
        filecapacity.setBounds(360, 170, 100, 20);

        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        getContentPane().add(closebtn);
        closebtn.setBounds(440, 250, 90, 23);

        getContentPane().add(sourcepath);
        sourcepath.setBounds(80, 20, 420, 20);

        filebrowsebtn1.setText("...");
        filebrowsebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebrowsebtn1ActionPerformed(evt);
            }
        });

        getContentPane().add(filebrowsebtn1);
        filebrowsebtn1.setBounds(500, 20, 30, 23);

        jLabel7.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel7.setText("Target File :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 110, 64, 15);

        getContentPane().add(targetfilepath);
        targetfilepath.setBounds(80, 110, 420, 20);

        filebrowsebtn3.setText("...");
        filebrowsebtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebrowsebtn3ActionPerformed(evt);
            }
        });

        getContentPane().add(filebrowsebtn3);
        filebrowsebtn3.setBounds(500, 110, 30, 23);

        showmsg.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        getContentPane().add(showmsg);
        showmsg.setBounds(80, 230, 350, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-540)/2, (screenSize.height-325)/2, 540, 325);
    }
    // </editor-fold>//GEN-END:initComponents

    private void filebrowsebtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebrowsebtn3ActionPerformed
// TODO add your handling code here:
            FileDialog fd=new FileDialog(this,"Open File",FileDialog.LOAD);
            fd.show();
            String s1=fd.getDirectory();
            String s2=fd.getFile();
            if(s1!=null&&s2!=null)
            targetfilepath.setText(s1+s2);
        
    }//GEN-LAST:event_filebrowsebtn3ActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void hidebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidebtnActionPerformed
// TODO add your handling code here:
        String pass=password.getText();
        String sp=sourcepath.getText();
        String bmpp=bmpfilepath.getText();
        String tp=targetfilepath.getText();
        
        if(pass.length()>0&&sp.length()>0&&bmpp.length()>0&&tp.length()>0)
        {
            try{
            FileInputStream f=new FileInputStream(sp);
            byte b[]=new byte[f.available()];
            f.read(b);
            f.close();
            String m=new String(b);
            
            filesize.setText(""+m.length()+" Bytes");
            File f1=new File(bmpp);
            bmpsize.setText(""+f1.length()+" Bytes");
            long capacity=(f1.length()-54)-32*8-4*8;
            capacity=capacity/8;
            filecapacity.setText(""+capacity+" Bytes");
            showmsg.setText("Hiding Message");
            
            Hide.Stegano(bmpp, tp,pass, m);
            }catch(Exception e)
            {
                    System.out.println(e);
            }
            showmsg.setText("Process Completed");           
        }
        else
        {
            System.out.println("Hello");
            showmsg.setText("Failed: Insufficient Data");
        }
    }//GEN-LAST:event_hidebtnActionPerformed

    private void filebrowsebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebrowsebtn2ActionPerformed
// TODO add your handling code here:
         FileDialog fd=new FileDialog(this,"Open File",FileDialog.LOAD);
            fd.show();
            String s1=fd.getDirectory();
            String s2=fd.getFile();
            if(s1!=null&&s2!=null)
            bmpfilepath.setText(s1+s2);
    }//GEN-LAST:event_filebrowsebtn2ActionPerformed

    private void filebrowsebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebrowsebtn1ActionPerformed
// TODO add your handling code here:
         FileDialog fd=new FileDialog(this,"Open Bitmap File",FileDialog.LOAD);
            fd.show();
            String s1=fd.getDirectory();
            String s2=fd.getFile();
            if(s1!=null&&s2!=null)
            sourcepath.setText(s1+s2);
        
    }//GEN-LAST:event_filebrowsebtn1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HideFile().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bmpfilepath;
    private javax.swing.JTextField bmpsize;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton filebrowsebtn1;
    private javax.swing.JButton filebrowsebtn2;
    private javax.swing.JButton filebrowsebtn3;
    private javax.swing.JTextField filecapacity;
    private javax.swing.JTextField filesize;
    private javax.swing.JButton hidebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel showmsg;
    private javax.swing.JTextField sourcepath;
    private javax.swing.JTextField targetfilepath;
    // End of variables declaration//GEN-END:variables
    
}
