
import java.io.*;
import java.awt.*;

/**
 *
 * @author  Administrator
 */
public class RecoverFile extends javax.swing.JFrame {
    
    /** Creates new form RecoverFile */
    public RecoverFile() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        targetfilepath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bmpfilepath = new javax.swing.JTextField();
        filebrowsebtn1 = new javax.swing.JButton();
        filebrowsebtn = new javax.swing.JButton();
        recoverbtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        filesize = new javax.swing.JTextField();
        bmpsize = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        showmsg = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recover File");
        getContentPane().add(targetfilepath);
        targetfilepath.setBounds(80, 100, 420, 20);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel1.setText("Target File :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 70, 15);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel2.setText("Bitmap File :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 30, 70, 15);

        getContentPane().add(bmpfilepath);
        bmpfilepath.setBounds(80, 30, 420, 20);

        filebrowsebtn1.setText("...");
        filebrowsebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebrowsebtn1ActionPerformed(evt);
            }
        });

        getContentPane().add(filebrowsebtn1);
        filebrowsebtn1.setBounds(500, 100, 30, 23);

        filebrowsebtn.setText("...");
        filebrowsebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebrowsebtnActionPerformed(evt);
            }
        });

        getContentPane().add(filebrowsebtn);
        filebrowsebtn.setBounds(500, 30, 30, 23);

        recoverbtn.setText("Recover ");
        recoverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoverbtnActionPerformed(evt);
            }
        });

        getContentPane().add(recoverbtn);
        recoverbtn.setBounds(440, 60, 90, 23);

        getContentPane().add(password);
        password.setBounds(80, 60, 360, 22);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 70, 15);

        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 140, 530, 10);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel4.setText("File Size :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 90, 15);

        filesize.setEditable(false);
        getContentPane().add(filesize);
        filesize.setBounds(170, 160, 100, 20);

        bmpsize.setEditable(false);
        getContentPane().add(bmpsize);
        bmpsize.setBounds(170, 190, 100, 20);

        jLabel5.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel5.setText("Bitmap Size :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 190, 90, 15);

        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        getContentPane().add(closebtn);
        closebtn.setBounds(440, 220, 90, 23);

        showmsg.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        getContentPane().add(showmsg);
        showmsg.setBounds(80, 220, 340, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-540)/2, (screenSize.height-285)/2, 540, 285);
    }
    // </editor-fold>//GEN-END:initComponents

    private void filebrowsebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebrowsebtn1ActionPerformed
// TODO add your handling code here:
         FileDialog fd=new FileDialog(this,"Open File",FileDialog.LOAD);
            fd.show();
            String s1=fd.getDirectory();
            String s2=fd.getFile();
            if(s1!=null&&s2!=null)
            targetfilepath.setText(s1+s2);
    }//GEN-LAST:event_filebrowsebtn1ActionPerformed

    private void filebrowsebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebrowsebtnActionPerformed
// TODO add your handling code here:
         FileDialog fd=new FileDialog(this,"Open File",FileDialog.LOAD);
            fd.show();
            String s1=fd.getDirectory();
            String s2=fd.getFile();
            if(s1!=null&&s2!=null)
            bmpfilepath.setText(s1+s2);
        
    }//GEN-LAST:event_filebrowsebtnActionPerformed

    private void recoverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoverbtnActionPerformed
// TODO add your handling code here:
        String pass=password.getText();
        String bmpp=bmpfilepath.getText();
        String tp=targetfilepath.getText();
        
        if(pass.length()>0&&bmpp.length()>0&&tp.length()>0)
        {
            try{
            Recover r=new Recover();
            r.Recover(bmpp);
            if(r.pass.equals(pass))
            {
            filesize.setText(""+r.msg.length()+" Bytes");
            File f1=new File(bmpp);
            bmpsize.setText(""+f1.length()+" Bytes");
            FileOutputStream f=new FileOutputStream(tp)        ;
            f.write(r.msg.getBytes());
            f.close();
            }
            else
                showmsg.setText("Invalid Password");
            }catch(Exception e)
            {
                    System.out.println(e);
            }
            showmsg.setText("Process Completed");           
        }
        else
        {
            
            showmsg.setText("Failed: Insufficient Data");
        }
        
    }//GEN-LAST:event_recoverbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
// TODO add your handling code here:
            dispose();
    }//GEN-LAST:event_closebtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverFile().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bmpfilepath;
    private javax.swing.JTextField bmpsize;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton filebrowsebtn;
    private javax.swing.JButton filebrowsebtn1;
    private javax.swing.JTextField filesize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton recoverbtn;
    private javax.swing.JLabel showmsg;
    private javax.swing.JTextField targetfilepath;
    // End of variables declaration//GEN-END:variables
    
}
