
import java.awt.*;


/**
 *
 * @author  Administrator
 */
public class RecoverMessage extends javax.swing.JFrame {
    
    /** Creates new form RecoverMessage */
    public RecoverMessage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        msgsize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        recoverbtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        filepath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        filebrowsebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        showmsg = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recover Message");
        msgsize.setEditable(false);
        getContentPane().add(msgsize);
        msgsize.setBounds(170, 270, 100, 20);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel4.setText("Message Size :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 270, 90, 15);

        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        getContentPane().add(closebtn);
        closebtn.setBounds(440, 330, 90, 23);

        recoverbtn.setText("Recover");
        recoverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoverbtnActionPerformed(evt);
            }
        });

        getContentPane().add(recoverbtn);
        recoverbtn.setBounds(440, 60, 90, 23);

        getContentPane().add(password);
        password.setBounds(80, 60, 360, 22);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 70, 15);

        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 240, 530, 10);

        getContentPane().add(filepath);
        filepath.setBounds(80, 20, 420, 20);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel2.setText("Bitmap File :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 15);

        filebrowsebtn.setText("...");
        filebrowsebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebrowsebtnActionPerformed(evt);
            }
        });

        getContentPane().add(filebrowsebtn);
        filebrowsebtn.setBounds(500, 20, 30, 23);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel1.setText("Message :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 60, 15);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        message.setMargin(new java.awt.Insets(5, 5, 0, 0));
        jScrollPane1.setViewportView(message);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 100, 450, 120);

        showmsg.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        getContentPane().add(showmsg);
        showmsg.setBounds(80, 320, 360, 15);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-540)/2, (screenSize.height-388)/2, 540, 388);
    }
    // </editor-fold>//GEN-END:initComponents

    private void recoverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoverbtnActionPerformed
// TODO add your handling code here:
        String pass=password.getText();
        String fp=filepath.getText();
             
        if(pass.length()>0&&fp.length()>0)
        {
            showmsg.setText("Process...");
            try{
            Recover r=new Recover();
            r.Recover(fp);
            
            showmsg.setText("Process Completed");           
            if(pass.equals(r.pass))
            {
                message.setText(r.msg);
                msgsize.setText(""+r.msg.length());
            }
            else
                showmsg.setText("Invalid Password");
            }
            catch(Exception e)
            {
                showmsg.setText("Failed");
            }
        }
        else
        {
            
            showmsg.setText("Failed: Insufficient Data");
        }
    }//GEN-LAST:event_recoverbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void filebrowsebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebrowsebtnActionPerformed
// TODO add your handling code here:
        FileDialog fd=new FileDialog(this,"Open Bitmap File",FileDialog.LOAD);
            fd.show();
            String s1=fd.getDirectory();
            String s2=fd.getFile();
            if(s1!=null&&s2!=null)
            filepath.setText(s1+s2);
    }//GEN-LAST:event_filebrowsebtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverMessage().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JButton filebrowsebtn;
    private javax.swing.JTextField filepath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField msgsize;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton recoverbtn;
    private javax.swing.JLabel showmsg;
    // End of variables declaration//GEN-END:variables
    
}
